from pygame.color import Color

DEFAULT_BORDER_WIDTH = 3
DEFAULT_BORDER_RADIUS = 4

DEFAULT_TEXT_COLOR = Color("white")
DEFAULT_UNHOVERED_BACKGROUND_COLOR = Color((30, 30, 30))
DEFAULT_HOVERED_BACKGROUND_COLOR = Color((40, 40, 40))
DEFAULT_SELECTED_BACKGROUND_COLOR = Color((60, 60, 60))
DEFAULT_BORDER_COLOR = Color("gray")
DEFAULT_TEXT_PADDING = 8
DEFAULT_TEXT_ANTIALIAS = True
